import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { svgFromName } from '../src/index.js';
import { optionsFromDb } from './util.js';

/**
 * Byte-level parity against the Dart implementation: every golden here was
 * generated by running the *Dart* `hiblob` package
 * (see `tools/generate_goldens.dart`) and capturing its exact SVG output.
 *
 * If one of these fails after a source change, the TypeScript output has
 * drifted from the Dart/Flutter version — that is a visual-contract break.
 * Regenerate the file from the Dart package, and only when the change was
 * deliberately mirrored on both sides.
 */

const goldensPath = join(
  dirname(fileURLToPath(import.meta.url)),
  'goldens.json',
);

type Golden = {
  key: string;
  name: string;
  options: Record<string, unknown>;
  svg: string;
};

type GoldenFile = {
  generator: string;
  entries: Golden[];
};

const corpus: GoldenFile = JSON.parse(readFileSync(goldensPath, 'utf8'));

const byKey = new Map(corpus.entries.map((e) => [e.key, e]));

describe('Dart parity goldens', () => {
  it('the corpus exists and is from the Dart generator', () => {
    expect(corpus.entries.length).toBeGreaterThan(0);
    expect(corpus.generator).toContain('dart');
  });

  it('the frozen snapshot golden matches the Dart byte-for-byte', () => {
    const golden = byKey.get('snapshot:ada@example.com');
    expect(golden).toBeDefined();
    const options = golden ? optionsFromDb(golden.options) : {};
    const svg = svgFromName('ada@example.com', options);
    expect(svg).toBe(golden?.svg);
  });

  for (const entry of corpus.entries) {
    it(`parity: ${entry.key}`, () => {
      const options = optionsFromDb(entry.options);
      expect(svgFromName(entry.name, options)).toBe(entry.svg);
    });
  }
});
